### ISSUE TITLE
Streams

### ISSUE THREAD

**Issue by boourns** [boourns/synthmodes#18]
requested

**Comment by delta-6400** [comment]
Attached are the SVG icons for streams
[streams_svg.zip](https://github.com/boourns/synthmodes/files/2897030/streams_svg.zip)

**Comment by delta-6400** [comment]
Main Modes:

---

Envelope Mode
VCFA w/ Internal Envelope 

Inputs
EXCITE - Trigger or gate input. Sensitive to changes in amplitude, duration, and slew rate of trigger.
IN - VCFA signal input.  Accepts CV and audio.  Normalled to +3.3v, so with nothing patched, sending triggers to EXCITEwill generate envelopes at output. 
LEVEL- Directly wired to VCA control input.  Opens and closes VCA portion of VCFA.

Controls
SHAPE - Controls shape of internal envelope; first it lengthens decay, then lengthens attack while decreasing decay, then it shortens both
MOD - Controls how the envelope affects the filter cutoff via depth and offset.  Fully CCW, the envelope does not affect Cutoff and the filter is fully closed.  At noon, the envelope fully opens and closes the filter.  As you increase past noon, depth of cutoff envelope decreases, but an offset is increasingly added so filter becomes more and more open without envelope. Fully CW, the filter is always fully open
LEVEL MOD - VCA control offset with nothing patched to Level.  Becomes attenuator for Level input when jack is patched.

---

Vactrol Mode
VCFA w/ Vactrol Responses

Inputs
EXCITE- Vactrol exciter.  Use trigs, gates, envelopes etc for typical LPG-style control of VCFA.  
IN - VCFA signal input.  Accepts CV and audio.  Normalled to +3.3v, so with nothing patched, sending modulation curves to Excite will "vactrolize" the modulation.  
LEVEL- Directly wired to VCA control input.  Opens and closes VCA portion of VCFA.

Controls
VCA CURVE - Should be linear for accurate vactrol responses... but play with it for other weird curves!
SHAPE - Controls vactrol response speed.  As SHAPE increases from fully CCW to noon, decay increases with small proprotional increase in attack.  From noon to fully CW, vactrol response occurs backwards in time (longer attack, shorter decay).
MOD - Controls how the filter cutoff tracks the amplitude modulation envelope; from fully CCW with no damping, to noon with full damping, to fully CW with no damping but an offset added to keep filter open.  
LEVEL MOD - VCA control offset with nothing patched to Level.  Becomes attenuator for Level input when jack is patched.

---

Follower Mode
Amplitude and Spectral Centroid Envelope Follower

Inputs
EXCITE - Signal to extract envelope information from.  Amplitude (loudness) is tracked, as well as spectral centroid (weighted mean of frequencies present in spectrum, with amplitudes of frequencies as weights - roughly how 'bright' a sound is). 
IN - Amplitude and Spectral Centroid envelopes of the EXCITE input are applied to this signal input so that the IN signal mimics the loudness and brightness of the EXCITE input.  Sending the same signal to EXCITE and IN allows for gating/expansion. With nothing patched, +3.3v normalled to IN,  so sending a signal to EXCITE allows for the envelope follower output to be reproduced at OUT.
LEVEL - Directly wired to VCA control input.  Opens and closes VCA portion of VCFA.

Controls
SHAPE - Controls how quickly the envelope follower tracks the EXCITE input. From fast (fully CCW) to muddy (noon) to wobbly (fully CW).
MOD - Controls how the filter cutoff tracks the spectral centroid envelope; from fully CCW with no tracking, to noon with full tracking, to fully CW with no damping but an offset added to keep filter open.  
LEVEL MOD - VCA control offset with nothing patched to Level.  Becomes attenuator for Level input when jack is patched.

---

Compressor Mode
Dynamics Compressor.
The compressor has a fast detector (0.2ms attack time, 150ms release time) and a hard knee.

Inputs
EXCITE - Side chain input.  If patched, then the level of the EXCITE input determines the amount of gain reduction to be applied to in.  If not patched, the mode operates as a typical compressor on IN. 
IN - Signal to be compressed. With nothing patched, +3.3v normalled to In, so sending a signal to Excite allows for the sidechain gain reduction envelope to be reproduced at OuT.
LEVEL- Directly wired to VCA control input.  Opens and closes VCA portion of VCFA.

Controls
VCA  Curve - Should be exponential for accurate compression.
SHAPE - Controls compression threshold.
MOD - At noon, no compression applied.  Turning CCW increases the compression but with no makeup gain, thus taming loud parts but leaving quiet untouched.  Turning CW from noon increases compression ratio but adds make up gain, thus boosting quiet parts but leaving loud parts untouched. 
LEVEL MOD - VCA control offset with nothing patched to Level.  Acts as an attenuator for LEVEL input when patched  Should be at minimum for accurate compression.

**Comment by delta-6400** [comment]
Alternate Modes:
Hold mode buttons until mode indicator light becomes red.
---

ASR Envelope Mode
VCFA w/ Internal ASR Envelope

Inputs
EXCITE - Trigger or gate input. Sensitive to changes in amplitude, duration, and slew rate of trigger. Gates hold envelope at max; release phase begins when envelope goes low.
IN - VCFA signal input. Accepts CV and audio. Normalled to +3.3v, so with nothing patched, sending triggers to EXCITEwill generate envelopes at output.
LEVEL- Directly wired to VCA control input. Opens and closes VCA portion of VCFA.

Controls
SHAPE - Controls shape of internal envelope; first it lengthens decay, then lengthens attack while decreasing decay, then it shortens both
MOD - Controls how the envelope affects the filter cutoff via depth and offset. Fully CCW, the envelope does not affect Cutoff and the filter is fully closed. At noon, the envelope fully opens and closes the filter. As you increase past noon, depth of cutoff envelope decreases, but an offset is increasingly added so filter becomes more and more open without envelope. Fully CW, the filter is always fully open
LEVEL MOD - VCA control offset with nothing patched to Level. Becomes attenuator for Level input when jack is patched.

---

Plucked Vactrol Mode
Pingable Vactrol LPG

Inputs
EXCITE - Acts as trigger input for pinging virtual vactrol..
IN - VCFA signal input. Accepts CV and audio. Normalled to +3.3v, so with nothing patched, sending a trig to EXCITE will output a "vactrolized" envelope.
LEVEL- Directly wired to VCA control input. Opens and closes VCA portion of VCFA.

Controls
VCA CURVE - Should be linear for accurate vactrol responses... but play with it for other weird curves!
SHAPE - Controls vactrol response speed. As SHAPE increases from fully CCW to noon, decay increases with small proprotional increase in attack. From noon to fully CW, vactrol response occurs backwards in time (longer attack, shorter decay).
MOD - Controls how the filter cutoff tracks the amplitude modulation envelope; from fully CCW with no damping, to noon with full damping, to fully CW with no damping but an offset added to keep filter open.
LEVEL MOD - VCA control offset with nothing patched to Level. Becomes attenuator for Level input when jack is patched.

---

Cutoff Controller Mode
Only tracks Cutoff (Spectral Centroid) Envelope

Inputs
EXCITE - Signal to extract envelope information from. Amplitude (loudness) is not tracked, only spectral centroid (weighted mean of frequencies present in spectrum, with amplitudes of frequencies as weights - roughly how 'bright' a sound is).
IN - Spectral Centroid envelope of the EXCITE input are applied to the IN signal input's amplitude.  With nothing patched, +3.3v normalled to IN, so sending a signal to EXCITE allows the "cutoff frequency" of the EXCITE input to be reproduced at OUT.
LEVEL - Directly wired to VCA control input. Opens and closes VCA portion of VCFA.

Controls
SHAPE - Controls how quickly the envelope follower tracks the EXCITE input. From fast (fully CCW) to muddy (noon) to wobbly (fully CW).
MOD - Controls how the filter cutoff tracks the spectral centroid envelope; from fully CCW with no tracking, to noon with full tracking, to fully CW with no damping but an offset added to keep filter open.
LEVEL MOD - VCA control offset with nothing patched to LEVEL. Becomes attenuator for LEVEL input when jack is patched.

---

Slow, Soft Compressor Mode
Dynamics Compressor.
The compressor has a slower detector and a softer knee than the default compressor.

Inputs
EXCITE - Side chain input. If patched, then the level of the EXCITE input determines the amount of gain reduction to be applied to in. If not patched, the mode operates as a typical compressor on IN.
IN - Signal to be compressed. With nothing patched, +3.3v normalled to In, so sending a signal to Excite allows for the sidechain gain reduction envelope to be reproduced at OuT.
LEVEL- Directly wired to VCA control input. Opens and closes VCA portion of VCFA.

Controls
VCA Curve - Should be exponential for accurate compression.
SHAPE - Controls compression threshold.
MOD - At noon, no compression applied. Turning CCW increases the compression but with no makeup gain, thus taming loud parts but leaving quiet untouched. Turning CW from noon increases compression ratio but adds make up gain, thus boosting quiet parts but leaving loud parts untouched.
LEVEL MOD - VCA control offset with nothing patched to LEVEL. Acts as an attenuator for LEVEL input when patched.  Should be at minimum for accurate compression.

---

Direct VCF and VCA Control Mode (All mode LEDs lit)
Independent control of Cutoff and Amplitude

Inputs
EXCITE - Filter cutoff control input.  Opens and closes VCF portion of VCFA
IN - Signal to amplify and filter
LEVEL- Directly wired to VCA control input. Opens and closes VCA portion of VCFA

Controls
SHAPE - Cutoff frequency offset control
MOD - Cutoff frequency attenuverter for EXCITE input.
LEVEL MOD - VCA control offset with nothing patched to LEVEL. Acts as an attenuator for LEVEL input when patched

**Comment by delta-6400** [comment]
Siamese Twins Modes
Hold both mode buttons to enter Siamese Twins modes; mode indicator LEDs will alternately blink.
---


Both channels are now linked, and share the same attack and decay time, controlled by the SHAPE knobs (Ch1 SHAPE = Atk, Ch2 SHAPE = Dec).  
All non-compressor siamese twin mode controls/inputs are identical to their standard counterparts except for SHAPE.

---

Siamese Twins Compressor
Ch1 SHAPE = Atk
Ch2 SHAPE = Rel
Ch1 MOD = Threshold
Ch2 MOD = Ratio & Makeup

**Comment by boourns** [comment]
Awesome, thank you!!  Will get this into next release

**Comment by boourns** [comment]
Added - thanks again!
