### ISSUE TITLE
Hemisphere Suite Vendor Name

### ISSUE THREAD

**Issue by Chysn** [boourns/synthmodes#56]
Thank you for including Hemisphere Suite in this product.

For future versions, can you please put Hemisphere Suite under the vendor name **Beige Maze** instead of Ornament and Crime? Hemisphere Suite is not Ornament and Crime, it just happens to run on the same hardware.

Thanks!
--Jason

**Comment by boourns** [comment]
Hi Jason,

Thanks for opening an issue.  I would like to satisfy your request in a way that still makes it obvious to end users that if they own an O&C module, that Hemisphere Suite is an option for them.  I don't want to impede discovery in the case this is the first time they've heard of Hemisphere Suite. 

The taxonomy currently in use in SynthModes is:

Hardware Manufacturer
- Module name (Firmware)

I think this is a good fit for the app because it aids discovery of new alternative firmwares for end users.

Ornament & Crime is not really a hardware manufacturer though, so it's already not a perfect fit.  But it seems to me that the name of the hardware module is Ornament & Crime.  If I look on modular grid that is what the module is called, although modular grid is not a great reference for O_C because every open source vendor adds their own listing with themselves as the manufacturer (calsynth, michigan synth works, plum audio, etc etc)

So, I'm open to ideas.

Cheers,
Tom

**Comment by Chysn** [comment]
Tom,

OK, your reasoning makes sense, and it's fine to leave it as it is. Thanks!

--Jason

**Comment by boourns** [comment]
Ok, thanks.

If you would like any changes to the 'Info' page on Hemisphere Suite, that would be another option for clarification or including the Beige Maze name. The current text is below, please suggest changes if you see fit:

```
Hemisphere Suite

Hemisphere Suite is an alternate firmware for the Ornament and Crime eurorack module.

Hemisphere Suite is an open-source project by Jason Justian (aka chysn).

Ornament and Crime is a collaborative open-source project by Patrick Dowling (aka pld), Max Stadler (aka mxmxmx) and Tim Churches (aka bennelong.bicyclist).

This cheat-sheet is based on the Hemisphere Suite Wiki which is under MIT license and used with permission.

```

**Comment by Chysn** [comment]
Tom, that description is fine. Thanks!
